project:
  type: website
  output-dir: docs

website:
  title: "Germán A. Tessmer"
  navbar:
    left:
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "CV"
        href: cv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
